//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FearlessFlight.XForms.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FearlessFlight.XForms.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fearless Flight.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper Alert.
        /// </summary>
        internal static string emotional_symptoms_hyper_alert {
            get {
                return ResourceManager.GetString("emotional_symptoms_hyper_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing Thoughts.
        /// </summary>
        internal static string emotional_symptoms_racing_thoughts {
            get {
                return ResourceManager.GetString("emotional_symptoms_racing_thoughts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking of Loves Ones.
        /// </summary>
        internal static string emotional_symptoms_thinking_of_loved_ones {
            get {
                return ResourceManager.GetString("emotional_symptoms_thinking_of_loved_ones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approach &amp; Landing.
        /// </summary>
        internal static string flight_stage_approach_and_landing {
            get {
                return ResourceManager.GetString("flight_stage_approach_and_landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the Gate.
        /// </summary>
        internal static string flight_stage_at_the_gate {
            get {
                return ResourceManager.GetString("flight_stage_at_the_gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bagge Claim.
        /// </summary>
        internal static string flight_stage_baggage_claim {
            get {
                return ResourceManager.GetString("flight_stage_baggage_claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boarding.
        /// </summary>
        internal static string flight_stage_boarding {
            get {
                return ResourceManager.GetString("flight_stage_boarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking In.
        /// </summary>
        internal static string flight_stage_checking_in {
            get {
                return ResourceManager.GetString("flight_stage_checking_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruising.
        /// </summary>
        internal static string flight_stage_cruising {
            get {
                return ResourceManager.GetString("flight_stage_cruising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs.
        /// </summary>
        internal static string flight_stage_customs {
            get {
                return ResourceManager.GetString("flight_stage_customs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deplaning.
        /// </summary>
        internal static string flight_stage_deplaning {
            get {
                return ResourceManager.GetString("flight_stage_deplaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent.
        /// </summary>
        internal static string flight_stage_descent {
            get {
                return ResourceManager.GetString("flight_stage_descent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting Secured Area.
        /// </summary>
        internal static string flight_stage_exiting_secured_area {
            get {
                return ResourceManager.GetString("flight_stage_exiting_secured_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home or at Destination.
        /// </summary>
        internal static string flight_stage_home_or_destination {
            get {
                return ResourceManager.GetString("flight_stage_home_or_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Week.
        /// </summary>
        internal static string flight_stage_one_week {
            get {
                return ResourceManager.GetString("flight_stage_one_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string flight_stage_security {
            get {
                return ResourceManager.GetString("flight_stage_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Off.
        /// </summary>
        internal static string flight_stage_take_off {
            get {
                return ResourceManager.GetString("flight_stage_take_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi In.
        /// </summary>
        internal static string flight_stage_taxi_in {
            get {
                return ResourceManager.GetString("flight_stage_taxi_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi Out.
        /// </summary>
        internal static string flight_stage_taxi_out {
            get {
                return ResourceManager.GetString("flight_stage_taxi_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string flight_stage_today {
            get {
                return ResourceManager.GetString("flight_stage_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string flight_stage_tomorrow {
            get {
                return ResourceManager.GetString("flight_stage_tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbulance.
        /// </summary>
        internal static string flight_stage_turbulance {
            get {
                return ResourceManager.GetString("flight_stage_turbulance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Weeks.
        /// </summary>
        internal static string flight_stage_two_weeks {
            get {
                return ResourceManager.GetString("flight_stage_two_weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline Safety.
        /// </summary>
        internal static string groundschool_01_airline_safety_title {
            get {
                return ResourceManager.GetString("groundschool_01_airline_safety_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet The Pilots.
        /// </summary>
        internal static string groundschool_02_meet_the_pilots_title {
            get {
                return ResourceManager.GetString("groundschool_02_meet_the_pilots_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport Security.
        /// </summary>
        internal static string groundschool_03_security_title {
            get {
                return ResourceManager.GetString("groundschool_03_security_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-Icing.
        /// </summary>
        internal static string groundschool_04_deicing_title {
            get {
                return ResourceManager.GetString("groundschool_04_deicing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi.
        /// </summary>
        internal static string groundschool_05_taxi_title {
            get {
                return ResourceManager.GetString("groundschool_05_taxi_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeoff.
        /// </summary>
        internal static string groundschool_06_takeoff_title {
            get {
                return ResourceManager.GetString("groundschool_06_takeoff_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruise.
        /// </summary>
        internal static string groundschool_07_cruise_title {
            get {
                return ResourceManager.GetString("groundschool_07_cruise_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbulence.
        /// </summary>
        internal static string groundschool_08_turbulence_title {
            get {
                return ResourceManager.GetString("groundschool_08_turbulence_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning.
        /// </summary>
        internal static string groundschool_09_lightning_title {
            get {
                return ResourceManager.GetString("groundschool_09_lightning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engines.
        /// </summary>
        internal static string groundschool_10_engines_title {
            get {
                return ResourceManager.GetString("groundschool_10_engines_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clouds.
        /// </summary>
        internal static string groundschool_11_clouds_title {
            get {
                return ResourceManager.GetString("groundschool_11_clouds_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approach &amp; Landing.
        /// </summary>
        internal static string groundschool_12_approach_and_landing_title {
            get {
                return ResourceManager.GetString("groundschool_12_approach_and_landing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs.
        /// </summary>
        internal static string groundschool_13_customs_title {
            get {
                return ResourceManager.GetString("groundschool_13_customs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string mainpage_button_about {
            get {
                return ResourceManager.GetString("mainpage_button_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Stage.
        /// </summary>
        internal static string mainpage_button_flightstage {
            get {
                return ResourceManager.GetString("mainpage_button_flightstage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground School.
        /// </summary>
        internal static string mainpage_button_groundschool {
            get {
                return ResourceManager.GetString("mainpage_button_groundschool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string mainpage_button_introduction {
            get {
                return ResourceManager.GetString("mainpage_button_introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Flight.
        /// </summary>
        internal static string mainpage_button_practiceflight {
            get {
                return ResourceManager.GetString("mainpage_button_practiceflight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Techniques.
        /// </summary>
        internal static string mainpage_button_techniques {
            get {
                return ResourceManager.GetString("mainpage_button_techniques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clenching Teeth.
        /// </summary>
        internal static string physical_symptoms_clenching_teeth {
            get {
                return ResourceManager.GetString("physical_symptoms_clenching_teeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Hands and Feet.
        /// </summary>
        internal static string physical_symptoms_cold_hands_and_feet {
            get {
                return ResourceManager.GetString("physical_symptoms_cold_hands_and_feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dizziness.
        /// </summary>
        internal static string physical_symptoms_dizziness {
            get {
                return ResourceManager.GetString("physical_symptoms_dizziness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Mouth.
        /// </summary>
        internal static string physical_symptoms_dry_mouth {
            get {
                return ResourceManager.GetString("physical_symptoms_dry_mouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headache.
        /// </summary>
        internal static string physical_symptoms_headache {
            get {
                return ResourceManager.GetString("physical_symptoms_headache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nausea.
        /// </summary>
        internal static string physical_symptoms_Nausea {
            get {
                return ResourceManager.GetString("physical_symptoms_Nausea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing Heart.
        /// </summary>
        internal static string physical_symptoms_racing_heart {
            get {
                return ResourceManager.GetString("physical_symptoms_racing_heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Speak Properly.
        /// </summary>
        internal static string physical_symptoms_speach_issues {
            get {
                return ResourceManager.GetString("physical_symptoms_speach_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweaty Palms.
        /// </summary>
        internal static string physical_symptoms_sweaty_palms {
            get {
                return ResourceManager.GetString("physical_symptoms_sweaty_palms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tense Muscles.
        /// </summary>
        internal static string physical_symptoms_tense_muscles {
            get {
                return ResourceManager.GetString("physical_symptoms_tense_muscles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 478.
        /// </summary>
        internal static string technique_478 {
            get {
                return ResourceManager.GetString("technique_478", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Spy.
        /// </summary>
        internal static string technique_ispy {
            get {
                return ResourceManager.GetString("technique_ispy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber Band.
        /// </summary>
        internal static string technique_rubber_band {
            get {
                return ResourceManager.GetString("technique_rubber_band", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Breathing.
        /// </summary>
        internal static string technique_simple_breathing {
            get {
                return ResourceManager.GetString("technique_simple_breathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tense and Relax.
        /// </summary>
        internal static string technique_tense_and_relax {
            get {
                return ResourceManager.GetString("technique_tense_and_relax", resourceCulture);
            }
        }
    }
}
